2019-05-05 14:23:23,746 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:46]
2019-05-05 14:23:37,210 : ERROR: Exception on /edit_profile [GET] [in /home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/shashi/Desktop/web/flask/app/routes.py", line 71, in edit_profile
    form = EditProfileForm()
TypeError: EditProfileForm() takes exactly 1 argument (0 given)
2019-05-05 14:33:50,003 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-05 14:33:53,407 : ERROR: Exception on /edit_profile [GET] [in /home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/shashi/Desktop/web/flask/app/routes.py", line 72, in edit_profile
    if form.validate_on_submit():
AttributeError: 'NoneType' object has no attribute 'validate_on_submit'
2019-05-05 14:36:56,108 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-05 14:37:01,573 : ERROR: Exception on /edit_profile [GET] [in /home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/shashi/Desktop/web/flask/app/routes.py", line 71, in edit_profile
    form = EditProfileForm()
TypeError: EditProfileForm() takes exactly 1 argument (0 given)
2019-05-05 14:38:15,205 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-05 14:38:19,439 : ERROR: Exception on /edit_profile [GET] [in /home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/shashi/Desktop/web/flask/app/routes.py", line 71, in edit_profile
    form = EditProfileForm()
TypeError: EditProfileForm() takes exactly 1 argument (0 given)
2019-05-05 14:38:52,239 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-05 14:38:53,865 : ERROR: Exception on /edit_profile [GET] [in /home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/shashi/Desktop/web/flask/app/routes.py", line 72, in edit_profile
    if form.validate_on_submit():
AttributeError: 'NoneType' object has no attribute 'validate_on_submit'
2019-05-05 14:51:57,241 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-05 14:52:12,392 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:04:53,136 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:05:14,231 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:05:31,654 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:06:31,735 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:08:11,055 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:08:21,361 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:08:27,269 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:24:49,642 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:24:55,288 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:27:46,718 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:32:09,488 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:52:41,303 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:53:14,792 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 16:59:33,469 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 17:00:32,687 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 17:00:37,935 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-06 17:00:55,913 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-08 20:36:40,966 : INFO: Blog Setup [in /home/shashi/Desktop/web/flask/app/__init__.py:47]
2019-05-08 20:37:42,821 : ERROR: Exception on /edit_profile [GET] [in /home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shashi/libs/anaconda3/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/shashi/Desktop/web/flask/app/routes.py", line 72, in edit_profile
    if form.validate_on_submit():
AttributeError: 'NoneType' object has no attribute 'validate_on_submit'
